### PR TITLE
Add schedule

### PR DESCRIPTION
**Pull request by tgxworld**
screenshot from 2016-05-09 00-00-47

screenshot from 2016-05-10 23 37 06

screenshot from 2016-05-10 23 37 36

### CODE REVIEW

**Comment by tgxworld** [comment]
@winston Lol consolidating all the info took longer than I thought. Will add in the schedule tomorrow.

**Comment by winston** [comment]
:ok:! :bow:

On Monday, 9 May 2016, Guo Xiang Tan notifications@github.com wrote:

> @winston https://github.com/winston Lol consolidating all the info took
> longer than I thought. Will add in the schedule tomorrow.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/reddotrubyconf/rdrc2016/pull/15#issuecomment-217729484

## 

Cheers,
Winston

**Comment by tgxworld** [comment]
@winston Please review! Thanks!

**Comment by winston** [comment]
🙇

**Pull request merged**
