### PR TITLE
Fix a src to a href for hyperlinks

### PR DESCRIPTION
**Pull request by sayanee**
The hyperlinks could not be clicked as the attributes were `src` instead of `href`:

For example:

image

### CODE REVIEW

**Comment by tgxworld** [comment]
:+1: lol I must have been very tired last night.

**Comment by JuanitoFatas** [comment]
👏  Merged manually as 980996d.

**Comment by tgxworld** [comment]
@JuanitoFatas Can you give me admin access to the repo? Thanks!

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas Can you give me admin access to the repo? Thanks!

I cannot. @winston can.

**Pull request closed without merging**
