### PR TITLE
Update Aaron Patterson's tagline

### PR DESCRIPTION
**Pull request by JuanitoFatas**
<blockquote class="twitter-tweet" data-lang="en-gb"><p lang="en" dir="ltr">Today is my last day at RedHat. I am extremely honored I could work with such a talented and passionate team. Thank you <a href="https://twitter.com/hashtag/coworkers?src=hash">#coworkers</a>! ❤️❤️</p>&mdash; Aaron Patterson (@tenderlove) <a href="https://twitter.com/tenderlove/status/713065076958187520">24 March 2016</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en-gb"><p lang="en" dir="ltr">I&#39;ve become a wizard because GitHub has given me a staff <a href="https://t.co/P5wP2gsFJM">pic.twitter.com/P5wP2gsFJM</a></p>&mdash; Aaron Patterson (@tenderlove) <a href="https://twitter.com/tenderlove/status/714513025470828544">28 March 2016</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

### CODE REVIEW

**Comment by winston** [comment]
Eh.. I thought I already changed in https://github.com/reddotrubyconf/rdrc2016/commit/ecd722427ab335d54467435006d1f5579211e339?

**Comment by tgxworld** [comment]
He posted 5 days ago :P

**Comment by winston** [comment]
Oh sorry! I totally didn't see this. :bow:

**Comment by winston** [comment]
By right the PR should fail though... Because of my update to master.

**Comment by JuanitoFatas** [comment]
> By right the PR should fail though... Because of my update to master.

GitHub heard you so they built: https://github.com/blog/2137-protected-branches-improvements

**Comment by winston** [comment]
lol.

**Pull request merged**
